### ISSUE TITLE
[1.19] Server crashes on start.

### ISSUE THREAD

**Issue by MrRagtime** [DakotaPride/Incantation#3]
> net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
> A potential solution has been determined:
> 	 - Replace mod 'Incantation' (incantation) 0.1.3 with any version that is compatible with:
> 		 - fabric 0.57.0+1.19

**Comment by DakotaPride** [comment]
please refer to Issue #2

**Comment by DakotaPride** [comment]
@MrRagtime 
Issue Should Now Be Resolved In [Incantation v0.1.4](https://www.curseforge.com/minecraft/mc-mods/incantation/files/3879823)
